# Generated by Django 3.2.7 on 2022-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220207_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_url',
            field=models.URLField(default=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='entered_eniac',
            field=models.IntegerField(default=32, max_length=10),
        ),
    ]
