# Generated by Django 3.2.7 on 2022-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220214_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
