# Generated by Django 3.2.7 on 2022-02-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220215_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
