# Generated by Django 3.2.7 on 2022-02-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220215_1839'),
        ('users', '0012_alter_user_entered_eniac'),
    ]

    operations = [
    ]
