# Generated by Django 3.2.7 on 2022-02-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220219_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
