# Generated by Django 2.2.5 on 2022-03-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220223_0934'),
        ('users', '0015_auto_20220219_2004'),
    ]

    operations = [
    ]
