# Generated by Django 3.2.7 on 2021-12-14 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('desc', models.TextField(default='', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('thumnail_img', models.ImageField(upload_to='')),
                ('tag', models.CharField(max_length=40)),
                ('git', models.CharField(max_length=60)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
