# Generated by Django 2.2.5 on 2021-12-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('desc', models.TextField(default='', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('thumnail_img', models.ImageField(upload_to='')),
                ('tag', models.CharField(max_length=40)),
                ('git', models.CharField(max_length=60)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
