# Generated by Django 3.2.7 on 2022-02-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.act_comment', verbose_name='댓글'),
        ),
    ]
