# Generated by Django 3.2.7 on 2022-01-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20211231_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
    ]
