# Generated by Django 3.2.7 on 2022-01-04 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='semester',
            field=models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], default='', max_length=10, null=True),
        ),
    ]
