# Generated by Django 3.2.7 on 2022-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_act_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.ManyToManyField(to='activities.Act_Comment', verbose_name='댓글'),
        ),
    ]
