# Generated by Django 3.2.7 on 2022-02-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='comment',
        ),
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Act_Comment', verbose_name='댓글'),
        ),
    ]
