# Generated by Django 3.2.7 on 2022-03-20 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='act_comment',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comm', to='activities.activity'),
        ),
    ]
