# Generated by Django 3.2.7 on 2022-04-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_activity_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act_comment',
            old_name='activities',
            new_name='activity',
        ),
    ]
