# Generated by Django 3.2.7 on 2022-05-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20220511_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='semester',
            field=models.CharField(choices=[('1학기', '22년도 1학기'), ('2학기', '22년도 2학기')], default='', max_length=10, null=True, verbose_name='학기'),
        ),
    ]
