# Generated by Django 3.2.7 on 2022-05-29 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0010_alter_activity_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
