# Generated by Django 3.2.7 on 2022-05-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_challenge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='img_a',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지1'),
        ),
        migrations.AddField(
            model_name='activity',
            name='img_b',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지2'),
        ),
        migrations.AddField(
            model_name='activity',
            name='img_c',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지3'),
        ),
    ]
