# Generated by Django 3.2.7 on 2022-02-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20220215_1839'),
        ('activities', '0013_activity_user'),
    ]

    operations = [
    ]
