# Generated by Django 3.2.7 on 2022-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_merge_0012_auto_20220215_1839_0013_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
