# Generated by Django 3.2.7 on 2022-02-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
