# Generated by Django 3.2.7 on 2022-02-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
