# Generated by Django 3.2.7 on 2022-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0002_alter_recommend_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='genre',
            field=models.CharField(blank=True, choices=[('웹', '웹'), ('앱', '앱'), ('AI', 'AI'), ('게임', 'GAME'), ('보안', '보안'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
    ]
