# Generated by Django 2.2.5 on 2022-02-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0005_alter_recommend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
