# Generated by Django 3.2.7 on 2022-02-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0009_alter_recommend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='lec_book',
            field=models.CharField(blank=True, choices=[('책', '강의'), ('책', '책')], max_length=20, null=True),
        ),
    ]
