# Generated by Django 3.2.7 on 2022-02-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0010_recommend_lec_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='level',
            field=models.CharField(blank=True, choices=[('입문', '입문'), ('주니어', '주니어')], max_length=20, null=True),
        ),
    ]
