# Generated by Django 3.2.7 on 2022-03-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0011_merge_20220301_1413'),
        ('recommends', '0011_recommend_level'),
    ]

    operations = [
    ]
