# Generated by Django 3.2.7 on 2022-03-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0012_merge_0011_merge_20220301_1413_0011_recommend_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
