# Generated by Django 3.2.7 on 2022-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0013_alter_recommend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='lec_book',
        ),
        migrations.AddField(
            model_name='recommend',
            name='lead',
            field=models.CharField(blank=True, choices=[('강의', '강의'), ('책', '책')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='level',
            field=models.CharField(blank=True, choices=[('입문', '입문'), ('중급이상', '중급이상')], max_length=20, null=True),
        ),
    ]
