# Generated by Django 3.2.7 on 2022-03-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0014_auto_20220312_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='desc',
            field=models.TextField(max_length=300, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='genre',
            field=models.CharField(blank=True, choices=[('웹', '웹'), ('앱', '앱'), ('AI', 'AI'), ('게임', 'GAME'), ('보안', '보안'), ('OTHER', 'OTHER')], max_length=20, null=True, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='lead',
            field=models.CharField(blank=True, choices=[('강의', '강의'), ('책', '책')], max_length=20, null=True, verbose_name='방식'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='level',
            field=models.CharField(blank=True, choices=[('입문', '입문'), ('중급이상', '중급이상')], max_length=20, null=True, verbose_name='레벨'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
