# Generated by Django 3.2.7 on 2022-01-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('thumnail_img', models.ImageField(upload_to='')),
                ('desc', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
