# Generated by Django 2.2.5 on 2022-03-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20220219_2004'),
        ('notices', '0002_auto_20220223_0934'),
    ]

    operations = [
    ]
