# Generated by Django 3.2.7 on 2022-01-03 01:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('notices', '0002_auto_20220103_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='tagging',
        ),
        migrations.AddField(
            model_name='notice',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
