# Generated by Django 3.2.7 on 2022-01-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20220103_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created']},
        ),
    ]
