# Generated by Django 3.2.7 on 2022-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('notices', '0003_remove_notice_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='tag',
            field=models.ManyToManyField(to='tags.Tag', verbose_name='태그'),
        ),
    ]
