# Generated by Django 3.2.7 on 2022-05-30 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20220313_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='img_a',
            field=models.ImageField(default=datetime.datetime(2022, 5, 30, 6, 44, 37, 192762, tzinfo=utc), upload_to='', verbose_name='이미지1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='img_b',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='이미지2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='img_c',
            field=models.ImageField(default=datetime.datetime(2022, 5, 30, 6, 44, 47, 873891, tzinfo=utc), upload_to='', verbose_name='이미지3'),
            preserve_default=False,
        ),
    ]
