# Generated by Django 3.2.7 on 2022-02-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_id'),
        ('notices', '0007_remove_notice_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='tag',
            field=models.ManyToManyField(to='tags.Tag', verbose_name='학년별'),
        ),
    ]
