# Generated by Django 3.2.7 on 2021-12-15 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(max_length=300)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chall_comments', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chall_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chall_comments',
            },
        ),
    ]
